"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import CarCard from "./CarCard";
import { AlertCircle, Loader2, Search, SlidersHorizontal } from "lucide-react";

type Filters = { search: string; brand: string; bodyType: string; transmissionType: string; fuelType: string; minYear: string; maxYear: string; minPrice: string; maxPrice: string; page: number };
const initialFilters: Filters = { search: "", brand: "", bodyType: "", transmissionType: "", fuelType: "", minYear: "", maxYear: "", minPrice: "", maxPrice: "", page: 1 };

export default function CarCatalog() {
  const [filters, setFilters] = useState<Filters>(initialFilters);
  const query = useQuery({ queryKey: ["public-cars", filters], queryFn: async () => (await api.get("/cars", { params: filters })).data, retry: 1, staleTime: 20_000 });
  const change = (key: keyof Filters, value: string | number) => setFilters((previous) => ({ ...previous, [key]: value, page: key === "page" ? Number(value) : 1 }));

  return <div className="container mx-auto px-4 py-8">
    <section className="mb-8 rounded-3xl bg-gradient-to-br from-blue-700 to-cyan-500 p-8 text-center text-white shadow-xl"><p className="mb-2 text-sm font-semibold uppercase tracking-[0.18em] text-blue-100">Database Referensi Kendaraan</p><h1 className="mb-3 text-3xl font-extrabold md:text-5xl">Car Information System</h1><p className="mx-auto max-w-2xl text-blue-50">Temukan spesifikasi lengkap, harga baru, estimasi harga bekas, dan fitur mobil dalam satu katalog.</p><div className="relative mx-auto mt-7 max-w-2xl"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={22} /><input value={filters.search} onChange={(event) => change("search", event.target.value)} placeholder="Cari merek atau model, misalnya Corolla, BR-V, atau EV..." className="w-full rounded-full py-4 pl-12 pr-5 text-slate-800 shadow-lg outline-none ring-blue-200 focus:ring-4" /></div></section>
    <div className="flex flex-col gap-8 md:flex-row"><aside className="w-full shrink-0 md:w-64"><div className="card sticky top-4 space-y-4"><div className="flex items-center gap-2 border-b pb-3 font-bold"><SlidersHorizontal size={19} /> Filter Spesifikasi</div><Field label="Merek"><input value={filters.brand} onChange={(event) => change("brand", event.target.value)} placeholder="Contoh: Toyota" className="input" /></Field><Field label="Tipe bodi"><select value={filters.bodyType} onChange={(event) => change("bodyType", event.target.value)} className="input"><option value="">Semua tipe bodi</option><option>SUV</option><option>MPV</option><option>Sedan</option><option>Hatchback</option><option>Pickup</option></select></Field><div className="grid grid-cols-2 gap-2"><Field label="Tahun min."><input type="number" value={filters.minYear} onChange={(event) => change("minYear", event.target.value)} className="input" /></Field><Field label="Tahun maks."><input type="number" value={filters.maxYear} onChange={(event) => change("maxYear", event.target.value)} className="input" /></Field></div><div className="grid grid-cols-2 gap-2"><Field label="Harga min."><input type="number" value={filters.minPrice} onChange={(event) => change("minPrice", event.target.value)} className="input" /></Field><Field label="Harga maks."><input type="number" value={filters.maxPrice} onChange={(event) => change("maxPrice", event.target.value)} className="input" /></Field></div><Field label="Transmisi"><select value={filters.transmissionType} onChange={(event) => change("transmissionType", event.target.value)} className="input"><option value="">Semua transmisi</option><option>Manual</option><option>Automatic</option><option>CVT</option><option>DCT</option></select></Field><Field label="Bahan bakar"><select value={filters.fuelType} onChange={(event) => change("fuelType", event.target.value)} className="input"><option value="">Semua bahan bakar</option><option>Bensin</option><option>Diesel</option><option>Hybrid</option><option>Listrik</option></select></Field><button onClick={() => setFilters(initialFilters)} className="w-full rounded-lg border border-blue-200 px-3 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-50">Reset filter</button></div></aside>
      <main className="min-w-0 flex-1">{query.isLoading ? <Loading /> : query.isError ? <section className="card flex min-h-64 flex-col items-center justify-center gap-3 text-center"><AlertCircle className="text-red-500" size={36} /><h2 className="font-bold">Katalog belum dapat dimuat</h2><p className="text-sm text-slate-500">Periksa koneksi API, lalu coba lagi. Halaman tidak akan berpindah atau crash.</p><button onClick={() => query.refetch()} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Coba lagi</button></section> : query.data?.items?.length ? <>{query.data.meta.searchNotice && <p className="mb-4 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">{query.data.meta.searchNotice}</p>}<p className="mb-4 text-sm text-slate-500">Menampilkan {query.data.items.length} dari {query.data.meta.total} data mobil</p><div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">{query.data.items.map((car: any) => <CarCard key={car._id} car={car} />)}</div>{query.data.meta.totalPages > 1 && <nav className="mt-8 flex items-center justify-center gap-3"><button disabled={filters.page <= 1} onClick={() => change("page", filters.page - 1)} className="rounded-lg border bg-white px-4 py-2 disabled:opacity-50">Sebelumnya</button><span className="text-sm font-medium">Halaman {filters.page} / {query.data.meta.totalPages}</span><button disabled={filters.page >= query.data.meta.totalPages} onClick={() => change("page", filters.page + 1)} className="rounded-lg border bg-white px-4 py-2 disabled:opacity-50">Selanjutnya</button></nav>}</> : <section className="card py-16 text-center"><h2 className="font-bold">Mobil tidak ditemukan</h2><p className="mt-2 text-sm text-slate-500">Ubah kata kunci atau reset filter untuk melihat semua data.</p></section>}</main></div>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-slate-700"><span className="mb-1 block">{label}</span>{children}</label>; }
function Loading() { return <div className="flex min-h-64 items-center justify-center"><Loader2 className="animate-spin text-blue-600" size={42} /></div>; }
